backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: images
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    format: "json"
    # folder: "content/pages" # The path to the folder where the documents are stored
    files:
      - name: "home"
        label: "Home"
        file: "content/pages/home.json"
        fields:
          - label: "Banner Section"
            name: "banner"
            widget: "object"
            fields:
              - label: "Slides"
                name: "slides"
                widget: "list"
                fields:
                  - { label: "Background Image", name: "backgroundImage", widget: "image" }
                  - { label: "Leap Image", name: "leapImage", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string", default: "Professional Styling Since 1990" }
                  - label: "Title"
                    name: "title"
                    widget: "object"
                    fields:
                      - { label: "Part 1", name: "part1", widget: "string", default: "The Essence" }
                      - { label: "Part 2", name: "part2", widget: "string", default: "Of Beauty" }
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - { label: "Text", name: "text", widget: "string", default: "Book Now" }
                      - { label: "Link", name: "link", widget: "string", default: "page-contact" }
                  - { label: "Image 1", name: "image1", widget: "image" }
                  - { label: "Image 2", name: "image2", widget: "image" }
                  - { label: "Style Title", name: "styleTitle", widget: "string", default: "Purerelax" }
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Background Image 1", name: "bgImage1", widget: "image" }
              - { label: "Background Image 2", name: "bgImage2", widget: "image" }
              - { label: "Background Image 3", name: "bgImage3", widget: "image" }
              - { label: "Background Image 4", name: "bgImage4", widget: "image" }
              - { label: "Main Image", name: "mainImage", widget: "image" }
              - label: "Experience Box"
                name: "experienceBox"
                widget: "object"
                fields:
                  - { label: "Background Image", name: "bgImage", widget: "image" }
                  - { label: "Years", name: "years", widget: "string" }
                  - { label: "Text", name: "text", widget: "string" }
              - label: "Content"
                name: "content"
                widget: "object"
                fields:
                  - { label: "Sub Title", name: "subTitle", widget: "string" }
                  - { label: "Title Part 1", name: "titlePart1", widget: "string" }
                  - { label: "Title Part 2", name: "titlePart2", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - label: "Features"
                    name: "features"
                    widget: "list"
                    fields:
                      - { label: "Text", name: "text", widget: "string" }
                      - { label: "Icon", name: "icon", widget: "image" }
              - label: "Author"
                name: "author"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Signature", name: "signature", widget: "image" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Designation", name: "designation", widget: "string" }
              - label: "Opening Hours"
                name: "openingHours"
                widget: "object"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Weekday Hours", name: "weekdayHours", widget: "string" }
                  - { label: "Saturday Hours", name: "saturdayHours", widget: "string" }
                  - { label: "Background Image", name: "bgImage", widget: "image" }
          - label: "Clients Section"
            name: "clients"
            widget: "object"
            fields:
              - label: "Clients"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Name", name: "name", widget: "string" }
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Background Image 1", name: "bgImage1", widget: "image" }
                  - { label: "Background Image 2", name: "bgImage2", widget: "image" }
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "Marquee Section"
            name: "marquee"
            widget: "object"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
          - label: "Video Section"
            name: "video"
            widget: "object"
            fields:
              - { label: "Background Image", name: "bgImage", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - { label: "Text", name: "text", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Video Element"
                name: "videoElement"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "YouTube Video ID", name: "videoId", widget: "string" }
          - label: "Gallery Section"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Side Images"
                name: "sideImages"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
              - label: "Main Image"
                name: "mainImage"
                widget: "object"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
          - label: "Pricing Section"
            name: "pricing"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
              - label: "Center Image"
                name: "centerImage"
                widget: "object"
                fields:
                  - { label: "Background Image", name: "bgImage", widget: "image" }
                  - { label: "Main Image", name: "image", widget: "image" }
              - label: "Pricing Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
                  - { label: "Price", name: "price", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Background Image", name: "bgImage", widget: "image" }
              - { label: "Top Shape Image", name: "topShapeImage", widget: "image" }
              - { label: "Bottom Shape Image", name: "bottomShapeImage", widget: "image" }
              - label: "Form"
                name: "form"
                widget: "object"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Description", name: "description", widget: "text" }
                  - { label: "Button Text", name: "buttonText", widget: "string" }
                  - label: "Fields"
                    name: "fields"
                    widget: "object"
                    fields:
                      - { label: "Name Placeholder", name: "namePlaceholder", widget: "string", default: "Name *" }
                      - { label: "Email Placeholder", name: "emailPlaceholder", widget: "string", default: "Email Address *" }
                      - { label: "Service Placeholder", name: "servicePlaceholder", widget: "string", default: "Select Service *" }
                      - { label: "Date Placeholder", name: "datePlaceholder", widget: "string", default: "Select Date *" }
                      - { label: "Date Format", name: "dateFormat", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
                      - { label: "Message Placeholder", name: "messagePlaceholder", widget: "string", default: "Write a Message" }

          - label: "Instagram Section"
            name: "instagram"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Alt Text", name: "alt", widget: "string" }

          - label: "Testimonial Section"
            name: "testimonial"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "object"
                fields:
                  - { label: "Icon", name: "icon", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
              - label: "Testimonials"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Text", name: "text", widget: "text" }
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Designation", name: "designation", widget: "string" }
                  - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
              - label: "Client Images"
                name: "clientImages"
                widget: "list"
                fields:
                  - { label: "Image", name: "image", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
                  - { label: "Alt Text", name: "alt", widget: "string" }
                  - { label: "Class Name", name: "className", widget: "string" }

      - name: "Header"
        label: "Header"
        file: "content/pages/header.json"
        fields:
          - label: "Top Bar"
            name: "topBar"
            widget: "object"
            fields:
              - { label: "Email", name: "email", widget: "string", default: "alma.lawson@example.com" }
              - { label: "Hours Text", name: "hoursText", widget: "string", default: "Mon to Sat: 9:00am – 6:00pm Sun: Closed" }
              - label: "Social Links"
                name: "socialLinks"
                widget: "list"
                fields:
                  - { label: "Platform", name: "platform", widget: "select", options: ["twitter", "facebook-f", "pinterest-p", "vimeo-v", "instagram"] }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "Logo"
            name: "logo"
            widget: "object"
            fields:
              - { label: "Light Logo", name: "light", widget: "image" }
              - { label: "Dark Logo", name: "dark", widget: "image" }
          - label: "Book Now Button"
            name: "bookNowButton"
            widget: "object"
            fields:
              - { label: "Text", name: "text", widget: "string", default: "Book Now" }
              - { label: "Link", name: "link", widget: "string", default: "page-contact" }
          - label: "Mobile Menu"
            name: "mobileMenu"
            widget: "object"
            fields:
              - { label: "Phone Number", name: "phone", widget: "string", default: "+92 (8800) - 98670" }
              - { label: "Email", name: "email", widget: "string", default: "help@company.com" }
              - { label: "Hours", name: "hours", widget: "string", default: "Mon - Sat 8:00 - 6:30, Sunday - CLOSED" }
          - label: "Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Link", name: "link", widget: "string" }
                  - label: "Submenu"
                    name: "submenu"
                    widget: "list"
                    required: false
                    fields:
                      - { label: "Label", name: "label", widget: "string" }
                      - { label: "Link", name: "link", widget: "string" }

      - name: "Footer"
        label: "Footer"
        file: "content/pages/footer.json"
        fields:
          - label: "Opening Hours"
            name: "openingHours"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", default: "Open Hours" }
              - label: "Hours"
                name: "hours"
                widget: "list"
                fields:
                  - { label: "Day", name: "day", widget: "string" }
                  - { label: "Time", name: "time", widget: "string" }
          - label: "Center Section"
            name: "center"
            widget: "object"
            fields:
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Social Links"
                name: "socialLinks"
                widget: "list"
                fields:
                  - { label: "Platform", name: "platform", widget: "select", options: ["twitter", "facebook-f", "pinterest-p", "vimeo-v"] }
                  - { label: "Link", name: "link", widget: "string" }
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string", default: "Contact" }
              - { label: "Address", name: "address", widget: "text" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "Bottom Bar"
            name: "bottomBar"
            widget: "object"
            fields:
              - { label: "Bottom Image", name: "bottomImage", widget: "image" }
              - { label: "Copyright Text", name: "copyrightText", widget: "string", default: "© Purerelax" }
              - { label: "Copyright Link", name: "copyrightLink", widget: "string", default: "Reserved By Kodesolution" }
              - { label: "Terms Link Text", name: "termsText", widget: "string", default: "Terms & Conditions" }
              - { label: "Terms Link", name: "termsLink", widget: "string", default: "/" }
