backend:
  name: git
  branch: main

local_backend: true

media_folder: "public/uploads" # Folder where uploaded files will be stored
public_folder: "/uploads"

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    format: "json"
    # folder: "content/pages" # The path to the folder where the documents are stored
    files:
      - name: "home"
        label: "Home"
        file: "content/pages/home.json"
        fields:
          - label: "Banner Section"
            name: "banner"
            widget: "object"
            fields:
              - label: "Slides"
                name: "slides"
                widget: "list"
                fields:
                  - { label: "Background Image", name: "backgroundImage", widget: "image" }
                  - { label: "Leap Image", name: "leapImage", widget: "image" }
                  - { label: "Sub Title", name: "subTitle", widget: "string", default: "Professional Styling Since 1990" }
                  - { label: "Title", name: "title", widget: "string", default: "The Essence Of Beauty" }
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - { label: "Text", name: "text", widget: "string", default: "Book Now" }
                      - { label: "Link", name: "link", widget: "string", default: "page-contact" }
                  - { label: "Image 1", name: "image1", widget: "image" }
                  - { label: "Image 2", name: "image2", widget: "image" }
                  - { label: "Style Title", name: "styleTitle", widget: "string", default: "Purerelax" }